/**
 * Token emitters.
 *
 * One source of truth, three consumers:
 *   - `buildCssVariables`  → CSS custom properties for the web app (light + dark)
 *   - `buildTailwindPreset`→ a Tailwind preset whose colors point at those vars
 *   - `buildNativeTheme`   → a plain resolved object for NativeWind / React Native,
 *                            which has no CSS variables and no rem unit
 *
 * Web colors resolve through CSS variables so a theme switch is one class on the
 * root. React Native gets fully resolved hexes per theme instead.
 */

import {
  borderWidth,
  breakpoint,
  categorical,
  duration,
  easing,
  fontFamily,
  fontSize,
  fontWeight,
  letterSpacing,
  radius,
  shadow,
  space,
  status,
  touchTarget,
  zIndex,
} from './primitives.js';
import { color } from './semantic.js';
import { setbackTreatment, stepFamilyStyle, STEP_FAMILIES } from './step-types.js';
import { tierStyle, VERIFICATION_TIERS } from './verification.js';

export type Theme = 'light' | 'dark';

/** kebab-cases a camelCase token name for use as a CSS custom property. */
const kebab = (s: string) => s.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`);

/**
 * Collects every themeable color as `[cssVarName, lightValue, darkValue]`.
 * Shared by the CSS and Tailwind emitters so the two can never drift.
 */
function themeableColors(): Array<[string, string, string]> {
  const out: Array<[string, string, string]> = [];

  for (const [name, pair] of Object.entries(color)) {
    out.push([`--color-${kebab(name)}`, pair.light, pair.dark]);
  }

  for (const family of STEP_FAMILIES) {
    const style = stepFamilyStyle[family];
    if (style.color) {
      out.push([`--step-${kebab(family)}`, style.color.light, style.color.dark]);
    }
  }
  out.push(['--setback-rule', setbackTreatment.rule.light, setbackTreatment.rule.dark]);
  out.push(['--setback-ink', setbackTreatment.ink.light, setbackTreatment.ink.dark]);

  for (const tier of VERIFICATION_TIERS) {
    const s = tierStyle[tier];
    out.push([`--tier-${tier}-fg`, s.fg.light, s.fg.dark]);
    out.push([`--tier-${tier}-bg`, s.bg.light, s.bg.dark]);
    out.push([`--tier-${tier}-border`, s.border.light, s.border.dark]);
  }

  for (const [name, pair] of Object.entries(status)) {
    out.push([`--status-${kebab(name)}`, pair.light, pair.dark]);
  }

  return out;
}

/**
 * Emits the stylesheet of custom properties.
 *
 * Dark values are declared under BOTH `@media (prefers-color-scheme: dark)` and
 * `:root[data-theme="dark"]`, with a `:not([data-theme="light"])` guard on the
 * media block, so an explicit user toggle wins in both directions.
 */
export function buildCssVariables(): string {
  const colors = themeableColors();
  const light = colors.map(([n, l]) => `  ${n}: ${l};`).join('\n');
  const darkDecls = colors.map(([n, , d]) => `  ${n}: ${d};`).join('\n');

  const scalars: string[] = [];
  for (const [k, v] of Object.entries(fontSize)) scalars.push(`  --text-${k}: ${v.rem};`);
  for (const [k, v] of Object.entries(fontSize)) scalars.push(`  --leading-${k}: ${v.lineHeight};`);
  for (const [k, v] of Object.entries(space)) scalars.push(`  --space-${String(k).replace('.', '_')}: ${v}px;`);
  for (const [k, v] of Object.entries(radius)) scalars.push(`  --radius-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(borderWidth)) scalars.push(`  --border-${k}: ${v}px;`);
  for (const [k, v] of Object.entries(shadow)) scalars.push(`  --shadow-${k}: ${v};`);
  for (const [k, v] of Object.entries(duration)) scalars.push(`  --duration-${k}: ${v}ms;`);
  for (const [k, v] of Object.entries(easing)) scalars.push(`  --ease-${k}: ${v};`);
  for (const [k, v] of Object.entries(fontWeight)) scalars.push(`  --weight-${k}: ${v};`);
  for (const [k, v] of Object.entries(letterSpacing)) scalars.push(`  --tracking-${k}: ${v};`);
  for (const [k, v] of Object.entries(zIndex)) scalars.push(`  --z-${k}: ${v};`);
  scalars.push(`  --font-ui: ${fontFamily.ui.join(', ')};`);
  scalars.push(`  --font-text: ${fontFamily.text.join(', ')};`);
  scalars.push(`  --font-mono: ${fontFamily.mono.join(', ')};`);
  scalars.push(`  --font-display: ${fontFamily.display.join(', ')};`);
  scalars.push(`  --touch-target-min: ${touchTarget.min}px;`);

  return `/* GENERATED by @precedent/ui-tokens — do not edit by hand.
   Edit packages/ui-tokens/src/*.ts and re-run \`npm run tokens\`. */

:root {
  color-scheme: light;
${light}
${scalars.join('\n')}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;
${darkDecls.split('\n').map((l) => `  ${l}`).join('\n')}
  }
}

:root[data-theme='dark'] {
  color-scheme: dark;
${darkDecls}
}

/* Timeline and filter motion degrade to instant, never to broken. */
@media (prefers-reduced-motion: reduce) {
  :root {
    --duration-fast: 0ms;
    --duration-base: 0ms;
    --duration-slow: 0ms;
  }
}
`;
}

/** Tailwind preset. Colors point at the CSS variables so theming stays in one place. */
export function buildTailwindPreset(): string {
  const colorEntries = themeableColors()
    .map(([varName]) => {
      const key = varName
        .replace(/^--/, '')
        .replace(/^color-/, '')
        .replace(/-/g, '-');
      return `      '${key}': 'var(${varName})',`;
    })
    .join('\n');

  const fontSizeEntries = Object.entries(fontSize)
    .map(([k, v]) => `      '${k}': ['${v.rem}', { lineHeight: '${v.lineHeight}' }],`)
    .join('\n');

  const spacingEntries = Object.entries(space)
    .map(([k, v]) => `      '${k}': '${v}px',`)
    .join('\n');

  const radiusEntries = Object.entries(radius)
    .map(([k, v]) => `      '${k}': '${typeof v === 'number' && v > 1000 ? '9999px' : `${v}px`}',`)
    .join('\n');

  return `/* GENERATED by @precedent/ui-tokens — do not edit by hand. */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', "[data-theme='dark']"],
  theme: {
    extend: {
      colors: {
${colorEntries}
      },
      fontFamily: {
        ui: [${fontFamily.ui.map((f) => `'${f}'`).join(', ')}],
        text: [${fontFamily.text.map((f) => `'${f}'`).join(', ')}],
        mono: [${fontFamily.mono.map((f) => `'${f}'`).join(', ')}],
        display: [${fontFamily.display.map((f) => `'${f}'`).join(', ')}],
      },
      fontSize: {
${fontSizeEntries}
      },
      spacing: {
${spacingEntries}
      },
      borderRadius: {
${radiusEntries}
      },
      screens: {
${Object.entries(breakpoint).map(([k, v]) => `        '${k}': '${v}px',`).join('\n')}
      },
      transitionDuration: {
${Object.entries(duration).map(([k, v]) => `        '${k}': '${v}ms',`).join('\n')}
      },
      transitionTimingFunction: {
${Object.entries(easing).map(([k, v]) => `        '${k}': '${v}',`).join('\n')}
      },
      boxShadow: {
${Object.entries(shadow).map(([k, v]) => `        '${k}': '${v}',`).join('\n')}
      },
    },
  },
  plugins: [],
};
`;
}

/**
 * Resolved theme object for React Native. No CSS variables, no rem — every value
 * is a concrete hex or number in device-independent pixels.
 */
export function buildNativeTheme(theme: Theme) {
  const resolve = <T extends { light: string; dark: string }>(pair: T) => pair[theme];

  return {
    theme,
    color: Object.fromEntries(
      Object.entries(color).map(([k, v]) => [k, resolve(v)]),
    ) as Record<keyof typeof color, string>,
    step: Object.fromEntries(
      STEP_FAMILIES.filter((f) => stepFamilyStyle[f].color).map((f) => [
        f,
        resolve(stepFamilyStyle[f].color!),
      ]),
    ) as Record<string, string>,
    setback: {
      rule: resolve(setbackTreatment.rule),
      ink: resolve(setbackTreatment.ink),
    },
    tier: Object.fromEntries(
      VERIFICATION_TIERS.map((t) => [
        t,
        {
          fg: resolve(tierStyle[t].fg),
          bg: resolve(tierStyle[t].bg),
          border: resolve(tierStyle[t].border),
          label: tierStyle[t].label,
          icon: tierStyle[t].icon,
        },
      ]),
    ),
    status: Object.fromEntries(
      Object.entries(status).map(([k, v]) => [k, resolve(v)]),
    ) as Record<keyof typeof status, string>,
    fontSize: Object.fromEntries(
      Object.entries(fontSize).map(([k, v]) => [k, v.px]),
    ) as Record<keyof typeof fontSize, number>,
    lineHeight: Object.fromEntries(
      Object.entries(fontSize).map(([k, v]) => [k, Math.round(v.px * v.lineHeight)]),
    ) as Record<keyof typeof fontSize, number>,
    fontWeight,
    fontFamily,
    space,
    radius,
    borderWidth,
    duration,
    touchTarget,
    zIndex,
  };
}

export const categoricalHues = categorical;
